version: "3.9"
services:
  database:
    container_name: database
    build: ./neo4j
    ports:
      - ":7687"
      - ":7474"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data/
      - neo4j_logs:/logs/
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "127.0.0.1:9334:9334"
    depends_on:
      - database
  frontend:
    container_name: frontend
    build:
      context: ./zkh-frontend
    ports:
      - "127.0.0.1:4202:4202"
    depends_on:
      - backend

volumes:
  neo4j_data:
  neo4j_logs: