version: "3.9"
services:
  database:
    container_name: database
    image: neo4j:5.14.0-community-bullseye
    env_file:
      - database.conf
    ports:
      - target: 7687
      - "127.0.0.1:7474:7474"
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "127.0.0.1:9334:9334"
    depends_on:
      - database
  frontend:
    container_name: frontend
    build:
      context: ./zkh-frontend
    ports:
      - "127.0.0.1:4202:4202"
    depends_on:
      - backend